spring:
  ## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
  datasource:
    url: jdbc:mariadb://172.17.0.2:3306/microservice
    username: root
    # Using environment variable ENCRYPT_KEY=ENCRYPT_KEY
    # Getting the value with POST localhost:8888/encrypt and the password in its body
    # Raw password: microservice
    password: techbro@123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        jdbc:
          lob:
            # With Java >= 9, to avoid:
            # SQLFeatureNotSupportedException: Method PgConnection.createClob() is not yet implemented
            non_contextual_creation: true
        # To include custom functions we want to use in HQL queries
        metadata_builder_contributor: com.pizza.configuration.persistence.SqlFunctionsMetadataBuilderContributor

security:
  restApi:
    authenticationInformation: http://localhost:5555/security/jwt/authinfo
    clientId: Spring5Microservices
    # Raw password: Spring5Microservices
    clientPassword: "{cipher}9f746b78f2d521d96cacf9fa65913048ef971dc242030ca5d8c7a56ddf90093cb58dfe71b66255df8ffe1d543680fe88"

rest:
  connect:
    timeoutInMilliseconds: 5000
  read:
    timeoutInMilliseconds: 30000
  write:
    timeoutInMilliseconds: 30000

cache:
  userBlacklist:
    entryCapacity: 20
    expireInSeconds: 600
    name: userBlackListCache